package com.sayan.fullstack.demospringbootangular.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name="Room")
public class RoomEntity {
	
	/**
	 * Autogenerated any time a new record is inserted into DB
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	
	@NotNull
	private Integer roomNumber;
	
	@NotNull
	private String price;
	
	@OneToMany(fetch=FetchType.EAGER,cascade=CascadeType.PERSIST)
	private List<ReservationEntity> listOfReservations;
		
	
	public RoomEntity() {
		super();
	}

	public RoomEntity(@NotNull Integer roomNumber, @NotNull String price) {
		super();
		this.roomNumber = roomNumber;
		this.price = price;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getRoomNumber() {
		return roomNumber;
	}

	public void setRoomNumber(Integer roomNumber) {
		this.roomNumber = roomNumber;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public List<ReservationEntity> getListOfReservations() {
		return listOfReservations;
	}

	public void setListOfReservations(List<ReservationEntity> listOfReservations) {
		this.listOfReservations = listOfReservations;
	}
	
	/**
	 * @param reservationEntity
	 * Helper method to create new list in case current is null
	 */
	public void addReservationEntity(ReservationEntity reservationEntity) {
		if(null==listOfReservations) {
			listOfReservations=new ArrayList<>();
		}
		listOfReservations.add(reservationEntity);
	}
	
}
